[package]
name = "chain-spec-generator"
version = "1.0.0"
authors = ["Paseo Core Team"]
edition = "2021"
repository = "https://github.com/paseo-network/runtimes.git"
license = "Apache License v2" # TODO

[dependencies]
clap = { version = "4.4.4", features = [ "derive" ] }
hex-literal = "0.4.1"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }

sc-chain-spec = "24.0.0"
polkadot-runtime-parachains = "4.0.0"
polkadot-primitives = "4.0.0"
sp-consensus-babe = "0.29.0"
sp-authority-discovery = "23.0.0"
sp-core = "25.0.0"
pallet-staking = "25.0.0"
sc-consensus-grandpa = "0.16.0"
pallet-im-online = "24.0.0"
sp-runtime = "28.0.0"
sp-consensus-beefy = "10.0.0"
xcm = { package = "staging-xcm", version = "4.0.0" }
parachains-common = { version = "4.0.0" }
cumulus-primitives-core = { version = "0.4.0" }

paseo-runtime = { path = "../relay/paseo" }
paseo-runtime-constants = { path = "../relay/paseo/constants" }


[features]
runtime-benchmarks = [
	"paseo-runtime/runtime-benchmarks",
]
